version: "3.8"

services:
  goodblast-backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=*
      - AWS_SECRET_ACCESS_KEY=*
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - redis
    container_name: goodblast-backend-container

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - "5672:5672"
      - "15672:15672"
    container_name: rabbitmq-container

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    container_name: redis-container
